--- 
- name: Configure GRE Tunnel
  hosts: routers
  gather_facts: no
  connection: network_cli
  vars_files:
    - ~/ansible-network-labs/vars.yml

  tasks:
  - name: create tunnel interface to R0
    ios_config:
      lines:
       - 'ip address 172.16.109.10 255.255.255.0'
       - 'tunnel source GigabitEthernet2'
       - 'tunnel destination 10.2.0.10'
       - 'description Tunnel to R0'
      parents: interface Tunnel 109
      
  - name: Configure OSPF
    ios_config:
      lines:
        - 'router-id 172.17.109.1'
        - 'passive-interface default'
        - 'network 0.0.0.0 0.0.0.0 area 0'
        - 'no passive-interface tunnel 109'
      parents: router ospf 1
